<?php

/**
 * Implementation of hook_libraries_info().
 */
function unmask_password_libraries_info() {
  return array(
    'show_password' => array(
      'name' => 'Show Password jQuery Plugin',
      'vendor url' => 'http://unwrongest.com/projects/show-password/',
      'download url' => 'http://showpassword.googlecode.com/files/jquery.showpassword-1.3.zip',
      'version arguments' => array(
        'file' => 'jquery.showpassword.js',
        'pattern' => '/@version(\t)+/',
        'lines' => 4,
      ),
      'files' => array(
        'js' => array(
          'jquery.showpassword.js',
        ),
      ),
    ),
  );
}

/**
 * Implementation of hook_element_info.
 */
function unmask_password_element_info() {
  return array(
    'unmask_password' => array(
      '#input' => TRUE,
      '#process' => array('unmask_password_process'),
      '#theme_wrappers' => array('form_element'),
      '#element_validate' => array('unmask_password_validate'),
    ),
  );
}

/**
 * Process callback for unmask_password Form API element.
 */
function unmask_password_process($element) {
  $element['pass'] =  array(
    '#type' => 'password', 
    '#value' => '', 
    '#required' => isset($element['#required']) ? $element['#required'] : TRUE,
    '#attributes' => array('data-typetoggle' => '#unmask_password_check_pass'),
    '#prefix' => '<div id="unmask_password_field">',
    '#suffix' => '</div>',
  );

  if (isset($element['#size'])) {
    $element['pass']['#size'] = $element['#size'];
  }
  
  $element['check_pass'] =  array(
    '#type' => 'checkbox',
    '#title' => t('Check Password'),
    '#attributes' => array('id' => 'unmask_password_check_pass'),
  );

  $element['#tree'] = TRUE;

  if (($library = libraries_load('show_password')) && !empty($library['loaded'])) {
    drupal_add_js($library['library path'] . '/jquery.showpassword.js');
    drupal_add_js(drupal_get_path('module', 'unmask_password') . '/js/unmask_password.js');
  } else {
    drupal_set_message(t('Show Password jQuery Plugin is not installed.'), 'error');
  }

  return $element;
}

/**
 * element_validate callback.
 */
function unmask_password_validate(&$element, &$form_state) {
  unset($form_state['values'][$element['#name']]['check_pass']);
  $form_state['values'][$element['#name']] = $form_state['values'][$element['#name']]['pass'];
}

